const mongoose = require('mongoose');

const claudeConversationSchema = new mongoose.Schema({
  title: { type: String, required: true }, // Auto-generated by Haiku
  question: { type: String, required: true },
  answer: { type: String, required: true },
  analysisDepth: { type: String, enum: ['quick', 'standard', 'deep', 'comprehensive'] },
  sourcesAnalyzed: { type: Number, default: 0 },
  filters: {
    platform: String,
    timeRange: String,
    startDate: Date,
    endDate: Date
  },
  options: {
    includePatterns: { type: Boolean, default: false },
    includeTrends: { type: Boolean, default: false }
  },
  usage: {
    inputTokens: Number,
    outputTokens: Number,
    model: String
  },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  createdAt: { type: Date, default: Date.now },
  isBookmarked: { type: Boolean, default: false }
});

// Index for faster queries
claudeConversationSchema.index({ createdAt: -1 });
claudeConversationSchema.index({ createdBy: 1, createdAt: -1 });
claudeConversationSchema.index({ title: 'text', question: 'text' });

module.exports = mongoose.model('ClaudeConversation', claudeConversationSchema);
