const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema({
  title: { type: String, required: true },
  snippet: { type: String, required: true },
  sourceUrl: { type: String, required: true },
  platform: { type: String, enum: ['Discord', 'Reddit', 'X', 'LinkedIn'] },
  taskType: { type: String, enum: ['response', 'post'], default: 'response' },
  intent: String, // e.g., "add chat to app", "pricing question"
  priority: { type: String, enum: ['low', 'medium', 'high'], default: 'medium' },
  isCompleted: { type: Boolean, default: false },
  completedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  completedAt: Date,
  isSkipped: { type: Boolean, default: false },
  skippedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  skippedAt: Date,
  skippedReason: String,
  delegatedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  delegatedAt: Date,
  suggestedResponse: String,
  responseVersions: [{
    content: String,
    savedAt: Date,
    versionNumber: Number
  }],
  currentVersion: { type: Number, default: 1 },
  reasoning: String, // AI reasoning for why this task was created
  metadata: {
    author: String,
    timestamp: Date,
    engagement: Number, // likes, comments, etc.
    sentiment: String,
    conversationId: mongoose.Schema.Types.ObjectId,
    originalPlatform: String,
    autoGenerated: Boolean,
    score: Number,
    // Post task specific fields
    personaName: String,
    postId: String,           // StandalonePost ID
    socialPostId: String,     // SocialPost ID (blog)
    blogPostId: String,       // BlogPost ID
    imageUrl: String,         // Generated image URL
    blogLinkUrl: String,      // Blog URL added at delegation
    blogLinkContent: String   // Modified content with blog link injected
  },
  createdAt: { type: Date, default: Date.now },
  foundByAgent: { type: Boolean, default: true }
});

// Index for faster queries
taskSchema.index({ isCompleted: 1, isSkipped: 1, priority: -1, createdAt: -1 });
taskSchema.index({ platform: 1 });
taskSchema.index({ intent: 1 });

module.exports = mongoose.model('Task', taskSchema);
